@startuml

skinparam linetype ortho

artifact "AS Device Profile" as device
artifact "AS HealthcareService activity" as healthcareserviceActivity
artifact "AS HealthcareService equipment" as healthcareserviceEquipment
artifact "AS Organization" as organization
artifact "AS Person" as person
artifact "AS Practitioner" as practitioner
artifact "AS PractitionerRole" as practitionerrole

url of device is  [[StructureDefinition-as-device.html]]
url of healthcareserviceActivity is  [[StructureDefinition-as-healthcareservice-healthcare-activity.html]]
url of healthcareserviceEquipment is  [[StructureDefinition-as-healthcareservice-social-equipment.html]]
url of organization [[StructureDefinition-as-organization.html]]
url of person [[StructureDefinition-as-person.html]]
url of practitioner [[StructureDefinition-as-practitioner.html]]
url of practitionerrole [[StructureDefinition-as-practitionerrole.html]]

' ##########
' # Device #
' ##########
device --> organization : owner 0..1


' #############################
' # healthcareserviceActivity #
' #############################
healthcareserviceActivity --> organization : providedBy 0..1

' ##############################
' # healthcareserviceEquipment #
' ##############################
healthcareserviceEquipment --> organization : providedBy 0..1


' ################
' # organization #
' ################
organization --> organization : partOf 0..1

' ##########
' # person #
' ##########
person --> practitioner : link 0..*


' ####################
' # practitionerrole #
' ####################

' organization
practitionerrole --> organization : organization 0..1

' practitioner
practitionerrole --> practitioner : practitioner 0..1


@enduml