# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.annuaire
canonical: https://interop.esante.gouv.fr/ig/fhir/annuaire
name: AnnuaireSante
title: "Annuaire Santé"
description: "Ressources de conformité basées sur le modèle d'exposition de l'Annuaire Santé."
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
  email: monserviceclient.annuaire@esante.gouv.fr
dependencies:
  hl7.fhir.fr.core: 2.1.0
  hl7.fhir.extensions.r5: 4.0.1
  hl7.terminology.r4: 5.5.0
status: active
version: 1.1.0-snapshot-4
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: qa-preview
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html