# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.annuaire
canonical: http://interop.esante.gouv.fr/ig/fhir/annuaire
name: Annuaire Santé
title: "Annuaire Santé"
description: "Ressources de conformité basé sur le modèle d'exposition de l'Annuaire Santé."
publisher:
  name: ANS
  url: https://esante.gouv.fr
  email: monserviceclient.annuaire@esante.gouv.fr
dependencies:
  hl7.fhir.fr.core: 1.1.0
status: draft
version: 0.0.3
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    autres_ressources.md:
        title: Autres Ressources
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Téléchargements et usage: downloads.html
        "Documentation sur les IG": new-tab https://interop.esante.gouv.fr/ig/documentation/
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html