# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.annuaire
canonical: https://interop.esante.gouv.fr/ig/fhir/annuaire
name: AnnuaireSante
title: "Annuaire Santé"
description: "Ressources de conformité basées sur le modèle d'exposition de l'Annuaire Santé."
publisher:
  name: ANS
  url: https://esante.gouv.fr
  email: monserviceclient.annuaire@esante.gouv.fr
dependencies:
  hl7.fhir.fr.core: 1.1.0
status: active
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: STU1

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    liste_profils.md:
        title: Liste des profils par permission
    # specifications_techniques.md:
    #     construction_des_flux.md:
    #     st_flux1.md:
    #         title: Flux 01
    #     st_flux2.md:
    #         title: Flux 02
    # specifications_fonctionnelles.md:
    #     sf_ajout.md:
    #         title: Fonctionnalité 1
    autres_ressources.md:
        title: Autres Ressources
    #     securite.md:
    #        title: Sécurité
        downloads.md:
            title: Téléchargements et usages

    # tests.md:
    #     title: Tests      
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Liste des profils: liste_profils.html
    # Description des flux:
    #     Construction des flux: construction_des_flux.html
    #     Flux 01: st_flux1.html
    #     Flux 02: st_flux2.html
    # Spécifications fonctionnelles:
    #     Spécifications fonctionnelles: specifications_fonctionnelles.html
    #     Fonctionnalité 1: sf_ajout.html
    Ressources de conformité: artifacts.html
    # Tests:   tests.html
    Autres ressources:
    #     Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Documentation sur les IG": new-tab https://interop.esante.gouv.fr/ig/documentation/
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html