# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.annuaire
canonical: https://interop.esante.gouv.fr/ig/fhir/annuaire
name: AnnuaireSante
title: "Annuaire Santé"
description: "Ressources de conformité basées sur le modèle d'exposition de l'Annuaire Santé."
publisher:
  name: ANS
  url: https://esante.gouv.fr
  email: monserviceclient.annuaire@esante.gouv.fr
dependencies:
  hl7.fhir.fr.core: 1.1.0
status: active
version: 1.0.0-ballot-2
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: STU1
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    liste_profils.md:
        title: Liste des profils par permission
    mapping.md:
        title: Vue globale de la modélisation MOS - FHIR

menu:
    Accueil: index.html
    Liste des profils: liste_profils.html
    Mapping FHIR/MOS: mapping.html
    Ressources de conformité: artifacts.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/