# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.annuaire
canonical: https://interop.esante.gouv.fr/ig/fhir/annuaire
name: AnnuaireSante
title: "Annuaire Santé"
description: "Ressources de conformité basées sur le modèle d'exposition de l'Annuaire Santé."
publisher:
  name: ANS
  url: https://esante.gouv.fr
  email: monserviceclient.annuaire@esante.gouv.fr
dependencies:
  hl7.fhir.fr.core: 1.1.0
  hl7.fhir.extensions.r5: 4.0.1
  ans.fr.nos: 1.1.0
status: active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    liste_profils.md:
        title: Liste des profils par permission
    mapping.md:
        title: Mappings MOS

menu:
    Accueil: index.html
    Liste des profils: liste_profils.html
    Mapping FHIR/MOS: mapping.html
    Ressources de conformité: artifacts.html
    Documentations: 
        Documentation des IGs: new-tab https://interop.esante.gouv.fr/ig/documentation/
        Documentation de l'API: https://ansforge.github.io/annuaire-sante-fhir-documentation/
        Code source de l'API: https://github.com/ansforge/annuaire-sante-fhir-serveur
        Issue sur l'API: https://github.com/ansforge/annuaire-sante-fhir-serveur/issues
        Issue sur l'IG: https://github.com/ansforge/annuaire-sante-fhir-documentation/issues